// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps (user_id, body, updated_at)
VALUES (
    $1,
    $2,
    now()
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChirpParams struct {
	UserID uuid.UUID
	Body   string
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp, arg.UserID, arg.Body)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
